
# --- DEFINIZIONE DEI DATI ---
QUARTIERI_CATANIA = {
    "Q_BARRIERA": "Barriera", 
    "Q_BICOCCA": "Bicocca", 
    "Q_BORGO": "Borgo",
    "Q_CANALICCHIO": "Canalicchio", 
    "Q_CAPPUCCINI": "Cappuccini", 
    "Q_CIBALI": "Cibali",
    "Q_CIVITA": "Civita", 
    "Q_CORSO_ITALIA": "Corso Italia", 
    "Q_FORTINO": "Fortino",
    "Q_LIBRINO": "Librino", 
    "Q_MONTE_PO": "Monte Po'", 
    "Q_NESIMA": "Nesima",
    "Q_OGNINA": "Ognina", 
    "Q_PIAZZA_DANTE": "Piazza Dante", 
    "Q_PICANELLO": "Picanello",
    "Q_PLAYA": "Playa", 
    "Q_SAN_CRISTOFORO": "San Cristoforo", 
    "Q_SAN_GIORGIO": "San Giorgio",
    "Q_SAN_LEONE": "San Leone", 
    "Q_SAN_NULLO": "San Nullo", 
    "Q_VIA_UMBERTO": "Via Umberto",
    "Q_AEROPORTO": "Zona Aeroporto", 
    "Q_TUTTA_CT": "Tutta Catania Centro"
}

COMUNI_PROVINCIA = {
    "COM_ACI_BONACCORSI": "Aci Bonaccorsi", 
    "COM_ACI_CASTELLO": "Aci Castello",
    "COM_ACI_CATENA": "Aci Catena", 
    "COM_ACI_SANT_ANTONIO": "Aci Sant'Antonio",
    "COM_ACIREALE": "Acireale", 
    "COM_ADRANO": "Adrano", 
    "COM_BELPASSO": "Belpasso",
    "COM_BIANCAVILLA": "Biancavilla", 
    "COM_BRONTE": "Bronte", 
    "COM_CALTAGIRONE": "Caltagirone",
    "COM_CAMPOROTONDO": "Camporotondo Etneo", 
    "COM_CASTEL_IUDICA": "Castel di Iudica",
    "COM_CASTIGLIONE": "Castiglione di Sicilia", 
    "COM_FIUMEFREDDO": "Fiumefreddo",
    "COM_GIARRE": "Giarre", 
    "COM_GRAMMICHELE": "Grammichele", 
    "COM_GRAVINA": "Gravina di Catania",
    "COM_LICODIA": "Licodia Eubea", 
    "COM_LINGUAGLOSSA": "Linguaglossa", 
    "COM_MALETTO": "Maletto",
    "COM_MANIACE": "Maniace", 
    "COM_MASCALI": "Mascali", 
    "COM_MASCALUCIA": "Mascalucia",
    "COM_MAZZARRONE": "Mazzarrone", 
    "COM_MILO": "Milo", 
    "COM_MINEO": "Mineo",
    "COM_MIRABELLA": "Mirabella Imbaccari", 
    "COM_MISTERBIANCO": "Misterbianco",
    "COM_MOTTA": "Motta Sant'Anastasia", 
    "COM_NICOLOSI": "Nicolosi", 
    "COM_PALAGONIA": "Palagonia",
    "COM_PATERNO": "Paternò", 
    "COM_PEDARA": "Pedara", 
    "COM_PIEDIMONTE": "Piedimonte Etneo",
    "COM_RAGALNA": "Ragalna", 
    "COM_RAMACCA": "Ramacca", 
    "COM_RANDAZZO": "Randazzo",
    "COM_RIPOSTO": "Riposto", 
    "COM_SAN_CONO": "San Cono", 
    "COM_SAN_GIOVANNI": "San Giovanni la Punta",
    "COM_SAN_GREGORIO": "San Gregorio", 
    "COM_SAN_MICHELE": "San Michele di Ganzaria",
    "COM_SAN_PIETRO": "San Pietro Clarenza", 
    "COM_SANT_AGATA": "Sant'Agata Li Battiati",
    "COM_SANT_ALFIO": "Sant'Alfio", 
    "COM_SANTA_MARIA": "Santa Maria di Licodia",
    "COM_SANTA_VENERINA": "Santa Venerina", 
    "COM_SCORDIA": "Scordia", 
    "COM_TRECASTAGNI": "Trecastagni",
    "COM_TREMESTIERI": "Tremestieri Etneo", 
    "COM_VALVERDE": "Valverde", 
    "COM_VIAGRANDE": "Viagrande",
    "COM_VIZZINI": "Vizzini", 
    "COM_ZAFFERANA": "Zafferana Etnea",
    "COM_TUTTI": "Tutti i comuni"
}

TOPIC_DISPONIBILI = {   
    "TOPIC_DOSSIER": "Dossier",
    "TOPIC_CRONACA": "Cronaca",
    "TOPIC_POILITICA": "Politica",
    "TOPIC_ATTUALITA": "Attualità",
    "TOPIC_SPORT": "Sport",
    "TOPIC_ECONOMIA" : "Economia e Lavoro",
    "TOPIC_ANNUNCI": "Annunci Lavoro",
    "TOPIC_METEO": "Meteo",
    "TOPIC_AMBIENTE": "Ambiente",
    "TOPIC_SALUTE": "Salute",
    "TOPIC_CASA": "Casa",
    "TOPIC_FORMAZIONE": "Formazione",
    "TOPIC_MOTORI": "Motori",
    "TOPIC_GUIDE": "Guide Catania",
    "TOPIC_TUTTI": "Tutti i topics"
}
